apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: monitoring  # This should be the namespace where Prometheus is deployed
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-exporter
  endpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - kafka  # This should match the namespace where your Kafka Exporter is deployed
